import { Outlet, Link } from 'react-router-dom'
import Header from './Header'

const FOOTER_LINKS = {
  Discover: [
    { to: '/', label: 'News Feed' },
    { to: '/digest', label: 'Daily Digest' },
    { to: '/topics', label: 'Topics' },
    { to: '/sources', label: 'Sources' },
  ],
  Company: [
    { to: '/about', label: 'About Us' },
    { to: '/editorial-standards', label: 'Editorial Standards' },
    { to: '/ai-use-policy', label: 'AI Use Policy' },
    { to: '/contact', label: 'Contact' },
  ],
  Legal: [
    { to: '/privacy-policy', label: 'Privacy Policy' },
    { to: '/terms', label: 'Terms of Use' },
    { to: '/advertising-policy', label: 'Advertising Policy' },
    { to: '/corrections-policy', label: 'Corrections Policy' },
  ],
}

export default function Layout() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <Header />
      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
        <Outlet />
      </main>

      <footer className="mt-20 border-t border-paper-200 bg-paper-50">
        <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6">
          <div className="grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-4">
            {/* Brand column */}
            <div>
              <Link to="/" className="flex items-center gap-2 mb-3">
                <span className="text-lg">🐦</span>
                <span className="font-serif font-semibold tracking-tight text-ink">Daily AI Bird</span>
              </Link>
              <p className="text-[13px] leading-relaxed text-ink-500">
                Today's AI in 5 minutes. Curated by AI, reviewed by humans —
                no hype, no ads, no <em>"prompt engineer"</em> threads.
              </p>
              <div className="mt-4 flex flex-wrap gap-1.5">
                <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-brand-600 border-b border-brand-300 pb-px">
                  AI-Assisted
                </span>
                <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-500">·</span>
                <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-500">
                  Editor-Reviewed
                </span>
              </div>
            </div>

            {/* Link columns */}
            {Object.entries(FOOTER_LINKS).map(([section, links]) => (
              <div key={section}>
                <p className="eyebrow mb-3">{section}</p>
                <ul className="space-y-2">
                  {links.map((l) => (
                    <li key={l.to}>
                      <Link
                        to={l.to}
                        className="text-[13px] text-ink-500 hover:text-ink transition-colors"
                      >
                        {l.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Bottom bar */}
        <div className="border-t border-paper-200 py-5">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-2 text-[12px] text-ink-500">
            <p>© {new Date().getFullYear()} Daily AI Bird</p>
            <p className="text-center">
              Summaries generated by AI · Reviewed by humans ·{' '}
              <Link to="/ai-use-policy" className="underline-grow hover:text-ink">AI Disclosure</Link>
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
