import { Outlet, Link } from 'react-router-dom'
import Header from './Header'

const FOOTER_LINKS = {
  Discover: [
    { to: '/', label: 'News Feed' },
    { to: '/digest', label: 'Daily Digest' },
    { to: '/topics', label: 'Topics' },
    { to: '/sources', label: 'Sources' },
  ],
  Company: [
    { to: '/about', label: 'About Us' },
    { to: '/editorial-standards', label: 'Editorial Standards' },
    { to: '/ai-use-policy', label: 'AI Use Policy' },
    { to: '/contact', label: 'Contact' },
  ],
  Legal: [
    { to: '/privacy-policy', label: 'Privacy Policy' },
    { to: '/terms', label: 'Terms of Use' },
    { to: '/advertising-policy', label: 'Advertising Policy' },
    { to: '/corrections-policy', label: 'Corrections Policy' },
  ],
}

export default function Layout() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main className="mx-auto max-w-7xl px-4 py-6">
        <Outlet />
      </main>

      <footer className="mt-16 border-t border-gray-100 bg-gray-50">
        {/* Main footer grid */}
        <div className="mx-auto max-w-7xl px-4 py-10">
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {/* Brand column */}
            <div>
              <Link to="/" className="flex items-center gap-2 mb-3">
                <span className="text-lg">🐦</span>
                <span className="font-bold text-gray-900 tracking-tight">Daily AI Bird</span>
              </Link>
              <p className="text-xs text-gray-500 leading-relaxed">
                AI-assisted news intelligence, reviewed by humans. The most important AI developments
                surfaced, summarised, and scored for you every day.
              </p>
              <div className="mt-4 flex flex-wrap gap-2">
                <span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-700">
                  🤖 AI-Assisted
                </span>
                <span className="rounded-full border border-green-200 bg-green-50 px-2.5 py-1 text-[10px] font-semibold text-green-700">
                  ✓ Editor-Reviewed
                </span>
              </div>
            </div>

            {/* Link columns */}
            {Object.entries(FOOTER_LINKS).map(([section, links]) => (
              <div key={section}>
                <p className="mb-3 text-[10px] font-bold tracking-widest text-gray-400 uppercase">{section}</p>
                <ul className="space-y-2">
                  {links.map((l) => (
                    <li key={l.to}>
                      <Link
                        to={l.to}
                        className="text-sm text-gray-500 hover:text-gray-900 transition-colors"
                      >
                        {l.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Bottom bar */}
        <div className="border-t border-gray-200 py-4">
          <div className="mx-auto max-w-7xl px-4 flex flex-col sm:flex-row items-center justify-between gap-2 text-xs text-gray-500">
            <p>© {new Date().getFullYear()} Daily AI Bird. All rights reserved.</p>
            <p className="text-center">
              Summaries generated by AI · Content reviewed by editorial team ·{' '}
              <Link to="/ai-use-policy" className="underline hover:text-gray-600">AI Disclosure</Link>
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
