"""
Curated catalog of known AI news sources.
Used by the "Find Sources" admin feature to suggest sources not yet in the DB.
"""

CATALOG: list[dict] = [
    # ── First-party AI Labs ───────────────────────────────────────────────────
    {
        "name": "OpenAI News",
        "slug": "openai-news",
        "url": "https://openai.com/news/",
        "feed_url": "https://openai.com/news/rss.xml",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Official news and research updates from OpenAI.",
        "tags": ["openai", "gpt", "research"],
    },
    {
        "name": "Anthropic News",
        "slug": "anthropic-news",
        "url": "https://www.anthropic.com/news",
        "feed_url": "https://www.anthropic.com/rss.xml",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Announcements, research and policy updates from Anthropic (makers of Claude).",
        "tags": ["anthropic", "claude", "safety"],
    },
    {
        "name": "Google DeepMind Blog",
        "slug": "deepmind-blog",
        "url": "https://deepmind.google/discover/blog/",
        "feed_url": "https://deepmind.google/blog/feed/basic",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Research and product updates from Google DeepMind.",
        "tags": ["deepmind", "google", "research"],
    },
    {
        "name": "Google AI Blog",
        "slug": "google-ai-blog",
        "url": "https://blog.research.google/",
        "feed_url": "https://blog.research.google/atom.xml",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Technical research from Google AI teams.",
        "tags": ["google", "research", "gemini"],
    },
    {
        "name": "Meta AI Blog",
        "slug": "meta-ai-blog",
        "url": "https://ai.meta.com/blog/",
        "feed_url": "https://ai.meta.com/blog/feed/",
        "scraper_type": "rss",
        "category": "blog",
        "description": "AI research and products from Meta (Llama, etc.).",
        "tags": ["meta", "llama", "research"],
    },
    {
        "name": "Microsoft AI Blog",
        "slug": "microsoft-ai-blog",
        "url": "https://blogs.microsoft.com/ai/",
        "feed_url": "https://blogs.microsoft.com/ai/feed/",
        "scraper_type": "rss",
        "category": "blog",
        "description": "AI products, partnerships and research from Microsoft.",
        "tags": ["microsoft", "copilot", "azure"],
    },
    {
        "name": "HuggingFace Blog",
        "slug": "huggingface-blog",
        "url": "https://huggingface.co/blog",
        "feed_url": "https://huggingface.co/blog/feed.xml",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Open-source AI models, datasets and tools news.",
        "tags": ["huggingface", "open-source", "models"],
    },
    {
        "name": "Mistral AI Blog",
        "slug": "mistral-blog",
        "url": "https://mistral.ai/news/",
        "feed_url": "https://mistral.ai/news/rss",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Model releases and updates from Mistral AI.",
        "tags": ["mistral", "models", "europe"],
    },
    {
        "name": "Cohere Blog",
        "slug": "cohere-blog",
        "url": "https://cohere.com/blog",
        "feed_url": "https://cohere.com/blog/feed.xml",
        "scraper_type": "rss",
        "category": "blog",
        "description": "Enterprise AI and NLP updates from Cohere.",
        "tags": ["cohere", "enterprise", "nlp"],
    },
    {
        "name": "NVIDIA AI Blog",
        "slug": "nvidia-ai-blog",
        "url": "https://blogs.nvidia.com/blog/category/artificial-intelligence/",
        "feed_url": "https://blogs.nvidia.com/blog/category/artificial-intelligence/feed/",
        "scraper_type": "rss",
        "category": "blog",
        "description": "AI hardware, software and research news from NVIDIA.",
        "tags": ["nvidia", "gpu", "hardware"],
    },
    {
        "name": "AWS Machine Learning Blog",
        "slug": "aws-ml-blog",
        "url": "https://aws.amazon.com/blogs/machine-learning/",
        "feed_url": "https://aws.amazon.com/blogs/machine-learning/feed/",
        "scraper_type": "rss",
        "category": "blog",
        "description": "AWS cloud AI/ML products, tutorials and case studies.",
        "tags": ["aws", "amazon", "cloud"],
    },
    # ── Tech News ─────────────────────────────────────────────────────────────
    {
        "name": "TechCrunch AI",
        "slug": "techcrunch-ai",
        "url": "https://techcrunch.com/category/artificial-intelligence/",
        "feed_url": "https://techcrunch.com/category/artificial-intelligence/feed/",
        "scraper_type": "rss",
        "category": "news",
        "description": "AI startup news, funding rounds and product launches.",
        "tags": ["startups", "funding", "products"],
    },
    {
        "name": "The Verge AI",
        "slug": "verge-ai",
        "url": "https://www.theverge.com/ai-artificial-intelligence",
        "feed_url": "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
        "scraper_type": "rss",
        "category": "news",
        "description": "Consumer AI, product reviews and industry analysis.",
        "tags": ["consumer", "products", "policy"],
    },
    {
        "name": "VentureBeat AI",
        "slug": "venturebeat-ai",
        "url": "https://venturebeat.com/category/ai/",
        "feed_url": "https://venturebeat.com/category/ai/feed/",
        "scraper_type": "rss",
        "category": "news",
        "description": "Enterprise AI news, analyses and executive interviews.",
        "tags": ["enterprise", "business", "analysis"],
    },
    {
        "name": "Wired AI",
        "slug": "wired-ai",
        "url": "https://www.wired.com/tag/artificial-intelligence/",
        "feed_url": "https://www.wired.com/feed/tag/ai/latest/rss",
        "scraper_type": "rss",
        "category": "news",
        "description": "Long-form AI journalism covering society, science and tech.",
        "tags": ["longform", "society", "policy"],
    },
    {
        "name": "MIT Technology Review AI",
        "slug": "mit-tech-review-ai",
        "url": "https://www.technologyreview.com/topic/artificial-intelligence/",
        "feed_url": "https://www.technologyreview.com/feed/",
        "scraper_type": "rss",
        "category": "news",
        "description": "In-depth AI reporting from MIT's tech publication.",
        "tags": ["academic", "research", "longform"],
    },
    {
        "name": "Ars Technica AI",
        "slug": "ars-technica-ai",
        "url": "https://arstechnica.com/ai/",
        "feed_url": "https://feeds.arstechnica.com/arstechnica/index",
        "scraper_type": "rss",
        "category": "news",
        "description": "Technical AI reporting for enthusiasts and professionals.",
        "tags": ["technical", "analysis", "products"],
    },
    {
        "name": "Reuters Technology",
        "slug": "reuters-tech",
        "url": "https://www.reuters.com/technology/artificial-intelligence/",
        "feed_url": "https://feeds.reuters.com/reuters/technologyNews",
        "scraper_type": "rss",
        "category": "news",
        "description": "Wire-service AI and tech news with global scope.",
        "tags": ["global", "business", "policy"],
    },
    {
        "name": "The Information AI",
        "slug": "the-information-ai",
        "url": "https://www.theinformation.com/technology/artificial-intelligence",
        "feed_url": None,
        "scraper_type": "rss",
        "category": "news",
        "description": "Premium insider AI business reporting (subscription).",
        "tags": ["insider", "business", "exclusive"],
    },
    {
        "name": "AI News",
        "slug": "ai-news-pub",
        "url": "https://www.artificialintelligence-news.com/",
        "feed_url": "https://www.artificialintelligence-news.com/feed/",
        "scraper_type": "rss",
        "category": "news",
        "description": "Dedicated AI news site covering industry and research.",
        "tags": ["industry", "products", "research"],
    },
    {
        "name": "Synced AI",
        "slug": "synced-ai",
        "url": "https://syncedreview.com/",
        "feed_url": "https://syncedreview.com/feed/",
        "scraper_type": "rss",
        "category": "news",
        "description": "AI research papers and industry news, strong on China AI.",
        "tags": ["research", "china", "papers"],
    },
    # ── Newsletters / Digests ─────────────────────────────────────────────────
    {
        "name": "The Batch (deeplearning.ai)",
        "slug": "the-batch",
        "url": "https://www.deeplearning.ai/the-batch/",
        "feed_url": "https://www.deeplearning.ai/the-batch/feed/",
        "scraper_type": "rss",
        "category": "newsletter",
        "description": "Weekly AI newsletter by Andrew Ng covering research and business.",
        "tags": ["newsletter", "weekly", "research"],
    },
    {
        "name": "Import AI",
        "slug": "import-ai",
        "url": "https://jack-clark.net/",
        "feed_url": "https://jack-clark.net/feed/",
        "scraper_type": "rss",
        "category": "newsletter",
        "description": "Weekly AI newsletter by Jack Clark (Anthropic co-founder).",
        "tags": ["newsletter", "weekly", "safety"],
    },
    {
        "name": "Ben's Bites",
        "slug": "bens-bites",
        "url": "https://bensbites.beehiiv.com/",
        "feed_url": "https://bensbites.beehiiv.com/feed",
        "scraper_type": "rss",
        "category": "newsletter",
        "description": "Daily AI news and tools roundup, very product-focused.",
        "tags": ["newsletter", "daily", "tools"],
    },
    {
        "name": "The Rundown AI",
        "slug": "rundown-ai",
        "url": "https://www.therundown.ai/",
        "feed_url": "https://www.therundown.ai/feed",
        "scraper_type": "rss",
        "category": "newsletter",
        "description": "Daily AI news briefing focused on practical applications.",
        "tags": ["newsletter", "daily", "practical"],
    },
    {
        "name": "Ahead of AI",
        "slug": "ahead-of-ai",
        "url": "https://magazine.sebastianraschka.com/",
        "feed_url": "https://magazine.sebastianraschka.com/feed",
        "scraper_type": "rss",
        "category": "newsletter",
        "description": "In-depth ML and LLM technical analysis by Sebastian Raschka.",
        "tags": ["newsletter", "technical", "llm"],
    },
    # ── Research ──────────────────────────────────────────────────────────────
    {
        "name": "arXiv cs.AI",
        "slug": "arxiv-cs-ai",
        "url": "https://arxiv.org/list/cs.AI/recent",
        "feed_url": "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending&max_results=30",
        "scraper_type": "arxiv",
        "category": "research",
        "description": "Latest AI research papers submitted to arXiv.",
        "tags": ["papers", "academic", "research"],
    },
    {
        "name": "arXiv cs.LG",
        "slug": "arxiv-cs-lg",
        "url": "https://arxiv.org/list/cs.LG/recent",
        "feed_url": "https://export.arxiv.org/api/query?search_query=cat:cs.LG&sortBy=submittedDate&sortOrder=descending&max_results=30",
        "scraper_type": "arxiv",
        "category": "research",
        "description": "Machine learning research papers on arXiv.",
        "tags": ["papers", "ml", "academic"],
    },
    {
        "name": "arXiv cs.CL",
        "slug": "arxiv-cs-cl",
        "url": "https://arxiv.org/list/cs.CL/recent",
        "feed_url": "https://export.arxiv.org/api/query?search_query=cat:cs.CL&sortBy=submittedDate&sortOrder=descending&max_results=30",
        "scraper_type": "arxiv",
        "category": "research",
        "description": "Natural language processing papers on arXiv.",
        "tags": ["papers", "nlp", "llm"],
    },
    {
        "name": "Papers With Code",
        "slug": "paperswithcode",
        "url": "https://paperswithcode.com/latest",
        "feed_url": None,
        "scraper_type": "playwright",
        "category": "research",
        "description": "ML papers with open-source implementations.",
        "tags": ["papers", "code", "open-source"],
    },
    {
        "name": "Stanford HAI",
        "slug": "stanford-hai",
        "url": "https://hai.stanford.edu/news",
        "feed_url": "https://hai.stanford.edu/news/feed",
        "scraper_type": "rss",
        "category": "research",
        "description": "AI policy, ethics and research from Stanford's Human-centered AI institute.",
        "tags": ["academic", "policy", "ethics"],
    },
    {
        "name": "Berkeley AI Research",
        "slug": "bair-blog",
        "url": "https://bair.berkeley.edu/blog/",
        "feed_url": "https://bair.berkeley.edu/blog/feed.xml",
        "scraper_type": "rss",
        "category": "research",
        "description": "Technical AI research posts from Berkeley AI Research lab.",
        "tags": ["academic", "research", "technical"],
    },
    # ── Policy & Safety ───────────────────────────────────────────────────────
    {
        "name": "Future of Life Institute",
        "slug": "fli-news",
        "url": "https://futureoflife.org/news/",
        "feed_url": "https://futureoflife.org/feed/",
        "scraper_type": "rss",
        "category": "policy",
        "description": "AI safety, policy and existential risk news.",
        "tags": ["safety", "policy", "existential-risk"],
    },
    {
        "name": "AI Safety Newsletter",
        "slug": "ai-safety-newsletter",
        "url": "https://newsletter.safe.ai/",
        "feed_url": "https://newsletter.safe.ai/feed",
        "scraper_type": "rss",
        "category": "policy",
        "description": "Weekly updates on AI safety research and policy.",
        "tags": ["safety", "newsletter", "alignment"],
    },
    {
        "name": "AI Now Institute",
        "slug": "ai-now-institute",
        "url": "https://ainowinstitute.org/news",
        "feed_url": "https://ainowinstitute.org/feed",
        "scraper_type": "rss",
        "category": "policy",
        "description": "Critical research on AI's social implications — labor, power, and accountability.",
        "tags": ["critical", "policy", "accountability", "labor"],
    },
    {
        "name": "The Markup",
        "slug": "the-markup",
        "url": "https://themarkup.org/",
        "feed_url": "https://themarkup.org/feeds/rss.xml",
        "scraper_type": "rss",
        "category": "policy",
        "description": "Data-driven investigative journalism on how tech companies affect society.",
        "tags": ["investigative", "accountability", "policy", "data"],
    },
    {
        "name": "AlgorithmWatch",
        "slug": "algorithmwatch",
        "url": "https://algorithmwatch.org/en/",
        "feed_url": "https://algorithmwatch.org/en/feed/",
        "scraper_type": "rss",
        "category": "policy",
        "description": "Watchdog organization monitoring algorithmic decision-making and AI policy in Europe.",
        "tags": ["europe", "policy", "watchdog", "algorithmic-accountability"],
    },
    {
        "name": "EFF Deeplinks",
        "slug": "eff-deeplinks",
        "url": "https://www.eff.org/deeplinks",
        "feed_url": "https://www.eff.org/rss/updates.xml",
        "scraper_type": "rss",
        "category": "policy",
        "description": "EFF's blog on digital rights, privacy, and AI/tech policy.",
        "tags": ["privacy", "rights", "policy", "surveillance"],
    },
    {
        "name": "404 Media",
        "slug": "404-media",
        "url": "https://www.404media.co/",
        "feed_url": "https://www.404media.co/rss/",
        "scraper_type": "rss",
        "category": "news",
        "description": "Independent tech journalism focused on surveillance, disinformation, and AI's societal impact.",
        "tags": ["investigative", "critical", "surveillance", "disinformation"],
    },
    {
        "name": "DAIR Institute",
        "slug": "dair-institute",
        "url": "https://www.dair-institute.org/blog",
        "feed_url": "https://www.dair-institute.org/blog/rss.xml",
        "scraper_type": "rss",
        "category": "policy",
        "description": "Research on AI ethics, harms, and justice from the Distributed AI Research Institute.",
        "tags": ["ethics", "justice", "accountability", "research"],
    },
    # ── Social / Community ────────────────────────────────────────────────────
    {
        "name": "Hacker News AI",
        "slug": "hackernews-ai",
        "url": "https://news.ycombinator.com",
        "feed_url": None,
        "scraper_type": "hn",
        "category": "social",
        "description": "Top AI-related posts from Hacker News (filtered by score).",
        "tags": ["community", "discussion", "technical"],
    },
    {
        "name": "Reddit r/MachineLearning",
        "slug": "reddit-ml",
        "url": "https://www.reddit.com/r/MachineLearning/",
        "feed_url": "https://www.reddit.com/r/MachineLearning/top.json?t=day&limit=25",
        "scraper_type": "reddit",
        "category": "social",
        "description": "Top posts from the largest ML community on Reddit.",
        "tags": ["community", "research", "discussion"],
    },
    {
        "name": "Reddit r/artificial",
        "slug": "reddit-artificial",
        "url": "https://www.reddit.com/r/artificial/",
        "feed_url": "https://www.reddit.com/r/artificial/top.json?t=day&limit=25",
        "scraper_type": "reddit",
        "category": "social",
        "description": "General AI discussion and news from r/artificial.",
        "tags": ["community", "general", "consumer"],
    },
    {
        "name": "Reddit r/LocalLLaMA",
        "slug": "reddit-localllama",
        "url": "https://www.reddit.com/r/LocalLLaMA/",
        "feed_url": "https://www.reddit.com/r/LocalLLaMA/top.json?t=day&limit=25",
        "scraper_type": "reddit",
        "category": "social",
        "description": "Open-source and local LLM news, tips and releases.",
        "tags": ["open-source", "local", "llm"],
    },
    {
        "name": "X — AI Accounts",
        "slug": "x-ai",
        "url": "https://x.com",
        "feed_url": None,
        "scraper_type": "twitter",
        "category": "social",
        "description": "AI announcements and discussions from major AI accounts on X (Twitter). Requires TWITTER_BEARER_TOKEN in .env.",
        "tags": ["twitter", "x", "announcements", "realtime"],
        "requires": "TWITTER_BEARER_TOKEN",
        "scrape_config": {
            "accounts": ["OpenAI", "AnthropicAI", "GoogleDeepMind", "MetaAI", "MistralAI", "huggingface", "karpathy", "sama"],
            "min_likes": 100,
        },
    },
]

CATEGORY_ORDER = ["blog", "news", "newsletter", "research", "policy", "social"]
CATEGORY_LABELS = {
    "blog": "AI Lab Blogs",
    "news": "Tech News",
    "newsletter": "Newsletters",
    "research": "Research",
    "policy": "Policy & Safety",
    "social": "Community",
}
