import { Link } from 'react-router-dom'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="mb-4 text-xl font-bold text-gray-900">{title}</h2>
      <div className="space-y-4 text-base text-gray-600 leading-relaxed">{children}</div>
    </section>
  )
}

export default function EditorialStandards() {
  return (
    <div className="mx-auto max-w-2xl py-4">
      <nav className="mb-6 text-xs text-gray-400">
        <Link to="/" className="hover:text-gray-600">Home</Link>
        <span className="mx-2">›</span>
        <Link to="/about" className="hover:text-gray-600">About</Link>
        <span className="mx-2">›</span>
        <span className="text-gray-600">Editorial Standards</span>
      </nav>

      <p className="mb-2 text-[11px] font-bold tracking-widest text-brand-600 uppercase">Transparency</p>
      <h1 className="mb-3 text-4xl font-extrabold tracking-tight text-gray-950">Editorial Standards</h1>
      <p className="mb-10 text-lg text-gray-500 leading-relaxed">
        How we select, process, and review content.
      </p>

      <Section title="Source Selection">
        <p>
          We monitor a curated list of sources that meet our quality bar: established research institutions,
          credible technology publications, official lab blogs, and reputable developer communities.
          Sources are added manually by our editorial team and reviewed quarterly.
        </p>
        <p>
          We do not accept paid source placement. A source cannot pay to be included in our monitoring list.
          Inclusion is based solely on editorial merit: accuracy track record, primary reporting quality,
          and relevance to the AI field.
        </p>
      </Section>

      <Section title="Article Selection Criteria">
        <p>Our editorial team approves articles that meet at least one of these criteria:</p>
        <ul className="ml-4 list-disc space-y-1.5">
          <li><strong>Research significance</strong> — new findings, benchmark results, or methods with meaningful implications</li>
          <li><strong>Product impact</strong> — launches, updates, or deprecations that materially affect developers or users</li>
          <li><strong>Policy relevance</strong> — regulatory developments, safety debates, or governance decisions</li>
          <li><strong>Open source momentum</strong> — significant releases or ecosystem shifts in open-source AI</li>
          <li><strong>Business intelligence</strong> — funding rounds, acquisitions, or strategic moves that reshape the competitive landscape</li>
        </ul>
      </Section>

      <Section title="What We Reject">
        <p>We do not publish:</p>
        <ul className="ml-4 list-disc space-y-1.5">
          <li>Pure opinion or speculation without factual basis</li>
          <li>Press releases republished without editorial value-add</li>
          <li>Clickbait or sensationalised AI coverage</li>
          <li>Articles that violate source credibility standards</li>
          <li>Duplicate stories — we surface the best version of a story when multiple sources cover the same event</li>
        </ul>
      </Section>

      <Section title="AI Processing Disclosure">
        <p>
          Every article summary displayed on Daily AI Bird was generated by an AI system and reviewed
          by a human editor. AI scores (relevance, impact, curiosity) are generated automatically and
          used to prioritise editorial review queues — they are not published as editorial opinions.
        </p>
        <p>
          If the AI summary contains an error, a factual inaccuracy, or misrepresents the source material,
          please use our <Link to="/corrections-policy" className="text-brand-600 hover:underline">corrections process</Link>.
        </p>
      </Section>

      <Section title="Conflicts of Interest">
        <p>
          Daily AI Bird has no financial relationships with the AI companies or organisations we cover.
          We do not accept sponsored content that is not clearly labelled as such. Advertising relationships
          do not influence editorial coverage — see our{' '}
          <Link to="/advertising-policy" className="text-brand-600 hover:underline">Advertising Policy</Link>.
        </p>
      </Section>

      <Section title="Updates & Corrections">
        <p>
          When we make a significant error, we correct it promptly and transparently. Minor corrections
          are noted inline. Significant corrections receive a correction notice at the top of the article.
          See our <Link to="/corrections-policy" className="text-brand-600 hover:underline">Corrections Policy</Link> for details.
        </p>
      </Section>
    </div>
  )
}
