import { useState } from 'react'
import { Link } from 'react-router-dom'

interface Props {
  compact?: boolean
}

export default function AIDisclosure({ compact = false }: Props) {
  const [expanded, setExpanded] = useState(false)

  if (compact) {
    return (
      <div className="flex items-center gap-2 text-xs text-gray-500">
        <span className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-amber-700 font-medium">
          <svg className="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 2a8 8 0 100 16A8 8 0 0010 2zm1 11H9v-2h2v2zm0-4H9V7h2v2z"/>
          </svg>
          AI-Assisted Summary
        </span>
        <Link to="/ai-use-policy" className="text-gray-400 hover:text-gray-600 transition-colors">
          What does this mean?
        </Link>
      </div>
    )
  }

  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full items-start justify-between gap-3 text-left"
      >
        <div className="flex items-center gap-2.5">
          <span className="text-lg leading-none">🤖</span>
          <div>
            <p className="text-sm font-semibold text-amber-900">AI-Assisted Content</p>
            <p className="text-xs text-amber-700 mt-0.5">
              This summary was generated by AI and reviewed by our editorial team.
            </p>
          </div>
        </div>
        <span className="mt-0.5 shrink-0 text-amber-600 text-xs font-medium">
          {expanded ? 'Less ↑' : 'More ↓'}
        </span>
      </button>

      {expanded && (
        <div className="mt-3 space-y-2 border-t border-amber-200 pt-3 text-xs text-amber-800 leading-relaxed">
          <p>
            Daily AI Bird uses Claude (Anthropic) to extract key points, generate summaries, and score articles for
            relevance, impact, and curiosity. Each processed article is queued for human editorial review before
            appearing on the site.
          </p>
          <p>
            AI may make mistakes. We do not endorse any claim made in the original source. Always read
            the original article before sharing or acting on information.
          </p>
          <Link
            to="/ai-use-policy"
            className="inline-block font-medium text-amber-900 underline underline-offset-2 hover:text-amber-700 transition-colors"
          >
            Read our full AI Use Policy →
          </Link>
        </div>
      )}
    </div>
  )
}
